### PR TITLE
Angular 17

### LINKED ISSUE #117: Angular 17
Hi! Thanks a lot for your great lib! Do you have any plans to update it for Angular v17?

### PR DESCRIPTION
**Pull request by tlebreton**
Hi

I made this pr to update your project with angular 17.

I take the opportunity to update all the packages except husky (breaking change after v4).

Thanks for your library :)

Closes #117

### CODE REVIEW

**Comment by kreuzerk** [comment]
Hi @tlebreton thx a lot for the changes. Very appreciated. The changes look good, but the commit message is not properly formatted. Having the proper conventional commit format is important since we use a fully automated release process. Means the commit message is analyzed and based on that the new version is calculated.

With this change the library can only be used with Angular 17 - (technically you could still use it with 16 but you would get install warnings or depending on the node version install errors).

Therefore I consider this change as a breaking change. This means that the commit message should by of type feat and include a commit body. A commit message could look something like this:

```
feat: migrate to Angular 17

BREAKING CHANGE: Angular 17
```

**Comment by kreuzerk** [comment]
Hi @tlebreton thx a lot for the changes. Very appreciated. The changes look good, but the commit message is not properly formatted. Having the proper conventional commit format is important since we use a fully automated release process. Means the commit message is analyzed and based on that the new version is calculated.

With this change the library can only be used with Angular 17 - (technically you could still use it with 16 but you would get install warnings or depending on the node version install errors).

Therefore I consider this change as a breaking change. This means that the commit message should by of type feat and include a commit body. A commit message could look something like this:

```
feat: migrate to Angular 17

BREAKING CHANGE: Angular 17
```

**Review by kreuzerk — CHANGES_REQUESTED** [review]
Hi @tlebreton thx a lot for the changes. Very appreciated. The changes look good, but the commit message is not properly formatted. Having the proper conventional commit format is important since we use a fully automated release process. Means the commit message is analyzed and based on that the new version is calculated.

With this change the library can only be used with Angular 17 - (technically you could still use it with 16 but you would get install warnings or depending on the node version install errors).

Therefore I consider this change as a breaking change. This means that the commit message should by of type feat and include a commit body. A commit message could look something like this:

```
feat: migrate to Angular 17

BREAKING CHANGE: Angular 17
```

**Comment by tlebreton** [comment]
Hi

Oups my bad ...

I amend my last commit and force push a new one. (if you want i can restart a new PR with somethink cleaner)

**Review by kreuzerk — APPROVED** [review]

**Pull request merged**
